name: mpt-7b-dolly

compute:
  cluster: r12z3
  gpus: 8

integrations:

- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_commit: v0.2.0
  pip_install: -e .[gpu]
  ssh_clone: false

command: |
  pip install hf_transfer
  export HF_HUB_ENABLE_HF_TRANSFER=1
  cd llm-foundry/scripts
  composer train/train.py /mnt/config/parameters.yaml

image: mosaicml/llm-foundry:2.0.1_cu118-latest

parameters:
  save_interval: 5ba
  save_num_checkpoints_to_keep: 1
  save_folder: ./checkpoints/{run_name}/

  max_seq_len: 2048

  global_seed: 17

  model:
     name: hf_causal_lm
     init_device: mixed
     pretrained_model_name_or_path: mosaicml/mpt-7b
     pretrained: true
     config_overrides:
       attn_config: 
         attn_impl: triton
         attn_uses_sequence_id: false

  tokenizer:
    name: mosaicml/mpt-7b
    kwargs:
      model_max_length: ${max_seq_len}

  train_loader:
    name: finetuning
    dataset:
      hf_name: mosaicml/dolly_hhrlhf
      split: train
      max_seq_length: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      shuffle: true
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0
  
  eval_loader:
    name: finetuning
    dataset:
      hf_name: mosaicml/dolly_hhr_lhf
      split: test
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      shuffle: false
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  scheduler:
    name: linear_decay_with_warmup
    t_warmup: 50ba
    alpha_f: 0

  optimizer:
    name: decoupled_lionw
    lr: 5.0e-6
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-8
    weight_decay: 0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 10ba
  eval_interval: 5ba
  eval_first: false
  eval_subset_num_batches: 10
  global_train_batch_size: 128
  seed: ${global_seed}
  device_eval_batch_size: 8
  device_train_microbatch_size: auto
  precision: amp_bf16

  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba
  python_log_level: debug

  callbacks:
    speed_monitor:
      window_size: 0

    lr_monitor: {}

    memory_monitor: {}

    runtime_estimator: {}